simulation.n=100
simulation.l=20.0
simulation.m=10
simulation.rc=1.0

simulation.radius.min=0.23
simulation.radius.max=0.26

simulation.periodic=false
simulation.random-seed=
simulation.input-mode=auto

simulation.input.static=input/static.txt
simulation.input.dynamic=input/dynamic.txt

simulation.output.neighbours=output/output.txt
simulation.output.time=output/time.txt
